name: Extractor Automatico de Tasas

on:
  schedule:
    # Se ejecuta todos los días a las 13:00 UTC (9:00 AM hora de Venezuela)
    # y a las 18:00 UTC (2:00 PM hora de Venezuela)
    - cron: '0 1,13 * * *'
  workflow_dispatch: # Esto te permite activar el script a mano desde la web de GitHub para probar

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    # 1. Copiar el código del repositorio a la máquina virtual
    - name: Clonar repositorio
      uses: actions/checkout@v4

    # 2. Instalar Python en la máquina virtual
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Instalar las librerías necesarias (como pandas, requests, beautifulsoup4, mysql-connector-python)
    - name: Instalar librerias
      run: |
        pip install --upgrade pip
        pip install requests beautifulsoup4 mysql-connector-python pandas sqlalchemy cryptography

    # 4. Ejecutar el script pasándole los secretos guardados en GitHub
    - name: Ejecutar script de extraccion
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: python IndexImportToSQL.py  # Cambia 'extractor.py' por el nombre real de tu script
